### PR TITLE
Add hyperpower2 plugin

### PR DESCRIPTION
**Pull request by razfriman**
Add `hyperpower2` plugin.

**Features:**
Customize particle effects
- Same color as the current cursor
- Rainbow colors
- Specify a list of colors
- Specify the min/max number of particles
- Specify the particle size

**NPM:**
https://www.npmjs.com/package/hyperpower2

**GitHub:**
https://github.com/razfriman/hyperpower

---

Sample configuration settings:

```
module.exports = {
  config: {
    // rest of the config
    hyperPower: {
      shake: false,
      colorMode: 'cursor', // 'cursor', 'custom', 'rainbow'
      colors: ['#eee'],
      particleSize: 3,
      minSpawnCount: 10,
      maxSpawnCount: 12,
      maximumParticles: 500
    }
  }
  // rest of the file
};
```

### CODE REVIEW

**Comment by razfriman** [comment]
@timothyis Let me know if there are any other steps to get this published

**Comment by razfriman** [comment]
Bump bump bump bump

**Comment by razfriman** [comment]
Anybody out there?

**Comment by timothyis** [comment]
Sorry @razfriman! There's a lot happening at Vercel! I'll cc @vassbence so we can get this in once tested. 👍

**Comment by vassbence** [comment]
Hey @razfriman, sorry for the delay. The plugin submission guidelines have been updated, you can [find them on the website now](https://hyper.is/store/submit) (basically we are hosting the preview images now instead of requiring a link). If you could merge master/fix conflicts and put the preview image in the repo I'd gladly test your plugin and include it ASAP if it's all good.

**Pull request closed without merging**
