### PR TITLE
Update theme screenshot URLs

### PR DESCRIPTION
**Pull request by mikemcbride**
Updating the URLs on the screenshots for my plugins, since RawGit is going away (so sad...)

### CODE REVIEW

**Comment by timothyis** [comment]
Interesting! I didn't know it was going away, thanks!

Just thinking out loud: Would it be better if you could submit the image to a static directory on this repo so that the link is always available as long as hyper-site is available?

**Comment by mikemcbride** [comment]
I was thinking about that this morning too. The only downside I see to that is that I can use the same jsdelivr link in the readme on my package and here. But that’s totally something I’d be willing to do.

**Comment by mikemcbride** [comment]
@timothyis I'm not sure why the CI check says "Need authorization to deploy" here. Thoughts on this?

re: hosting images on the static directory, do you think we could just use the `/static` folder that Next gives us and update the URLs in the `preview` property to be `/static/my-image.jpg`?

**Comment by vassbence** [comment]
This idea has actually been implemented @mikemcbride, [ the updated guide](https://hyper.is/store/submit) will tell you where to put the images.

**Pull request closed without merging**
